<?php

$adminka = '/organizer';

$pix_width = 600;
$pix_height = 800;
$pix_size = 8388608;

$req_art_fields = array('name','img_url');
$show_art_fields = array('Название'=>'name', 'Описание'=>'desc', 'Картинка'=>'img_url', 'Превью'=>'prev_url', 'Раздел'=>'part');
//('Название'=>'name', 'Описание'=>'desc', 'Картинка'=>'img_url', 'Превью'=>'prev_url', 'Цена'=>'price', 'Раздел'=>'part', 'Спец'=>'spec', 'Количество'=>'number', 'Статус'=>'status')

$part_name = array(1=>'improvisation', 2=>'character', 3=>'illustration');
$nameitem = array('рисунок', 'рисунков', 'рисунка');


?>