<?php

$adminka = '/organizer';

$pix_width = 600;
$pix_height = 800;
$pix_size = 3000000;

$req_art_fields = array('name','img_url');
$show_art_fields = array('Название'=>'name', 'Описание'=>'desc', 'Картинка'=>'img_url', 'Раздел'=>'part');
//('Название'=>'name', 'Описание'=>'desc', 'Картинка'=>'img_url', 'Цена'=>'price', 'Раздел'=>'part', 'Спец'=>'spec', 'Количество'=>'number', 'Статус'=>'status')

$part_name = array(1=>'illustration', 2=>'lettering', 3=>'improvisation');
$nameitem = array('рисунок', 'рисунков', 'рисунка');

?>